### ISSUE TITLE
Repeated line in pcl_conversions.h moveFromPCL() (line 406 in hydro-devel, 436 in indigo-devel)

### ISSUE THREAD

**Issue by mabelzhang** [ros-perception/pcl_conversions#19]
Line 406 in `pcl_conversions.h` in `hydro-devel` seems to repeat the line before it:

```
   void moveFromPCL(pcl::PolygonMesh &pcl_mesh, pcl_msgs::PolygonMesh &mesh)
    moveFromPCL(pcl_mesh.cloud, mesh.cloud);
    moveFromPCL(pcl_mesh.cloud, mesh.cloud);
```

From other functions around it, looks like the last line should be `pcl_mesh.polygon` and `mesh.polygon`, instead of `.cloud`.

Similar thing is in indigo-devel 436:

https://github.com/ros-perception/pcl_conversions/blob/indigo-devel/include/pcl_conversions/pcl_conversions.h#L431-L437

**Comment by wjwwood** [comment]
@mabelzhang I agree with you and thanks for letting us know. I'm sure that @paulbovbel would be willing to look into that, but a pull request might help us get it merged and released sooner.
