### ISSUE TITLE
Lunar release

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-perception/pcl_conversions#25]
Hi @paulbovbel and `pcl_conversions` maintainers!

As mentionned in https://github.com/ros-perception/pcl_msgs/issues/7, it would be great to have this package released into Lunar asap to unblock the release of the navigation stack and all downstream packages. If you don't have time to make a new release, please run bloom to release 2.0.1 for Lunar.

Thanks!

**Comment by wkentaro** [comment]
I tested on docker and it has successfully been built on XYZ with following changes:

- https://github.com/ros/rosdistro/pull/14524

**Memo**

```
sudo docker run -it ubuntu:yakkety /bin/bash

apt update
apt install sudo aptitude vim lsb-release python python-pip python-rosdep dirmngr
sudo pip install catkin-tools

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

cd
mkdir -p pcl_conversions_ws/src
cd pcl_conversions_ws/src
git clone https://github.com/ros-perception/pcl_conversions.git

rosdep init && rosdep update
rosdep install --from-path . -r -y
catkin build pcl_conversions
```

**Comment by wkentaro** [comment]
@paulbovbel How can I release that? Do I have the access to the release repo?

**Comment by mikaelarguedas** [comment]
@wkentaro I sent you an invite to the PCL_Team on ros-gbp that should give you access to all the release repositories you need to release PCL related ros packages

**Comment by wkentaro** [comment]
Ok, Thanks.

**Comment by paulbovbel** [comment]
This is interesting. I see that pcl_conversion's package xml has:

```
  <build_depend>libpcl-all-dev</build_depend>

  <run_depend>libpcl-all</run_depend>
  <run_depend>libpcl-all-dev</run_depend>
```

whereas in 'good practice', I would have expected:

```
  <build_depend>libpcl-all-dev</build_depend>

  <run_depend>libpcl-all</run_depend>
```
in which case, you don't install the dev dependencies unless you're building the package. This is the difficulty I was referring to in https://github.com/ros-perception/perception_pcl/issues/130. For yakkety/zesty, there is no libpcl1.8 package:

```
libpcl-all:
    xenial: [libpcl1.7]
```

So there's a few options here. Looking at the pcl_conversions CMakeLists:

https://github.com/ros-perception/pcl_conversions/blob/indigo-devel/CMakeLists.txt#L6

I suspect the only exec_dependency we need is `libpcl-common1.8` (from http://packages.ubuntu.com/search?keywords=libpcl)

The unpleasant alternative of course, is to remove `libpcl-all` as a concept in lunar, and always install dev dependencies.

**Comment by wkentaro** [comment]
How about this?

```
% rosdep resolve libpcl-all --os=ubuntu:yakkety
#apt
libpcl-apps1.8 libpcl-common1.8 libpcl-features1.8 libpcl-filters1.8 libpcl-io1.8 libpcl-kdtree1.8 libpcl-keypoints1.8 libpcl-ml1.8 libpcl-octree1.8 libpcl-outofcore1.8 libpcl-people1.8 libpcl-recognition1.8 libpcl-registration1.8 libpcl-sample-consensus1.8 libpcl-search1.8 libpcl-segmentation1.8 libpcl-stereo1.8 libpcl-surface1.8 libpcl-tracking1.8 libpcl-visualization1.8
```

with this change:

```
diff --git a/rosdep/base.yaml b/rosdep/base.yaml
index 83520d5..fda7b68 100644
--- a/rosdep/base.yaml
+++ b/rosdep/base.yaml
@@ -2185,6 +2185,48 @@ libpcl-all:
     vivid: [libpcl1.7]
     wily: [libpcl1.7]
     xenial: [libpcl1.7]
+    yakkety:
+      - libpcl-apps1.8
+      - libpcl-common1.8
+      - libpcl-features1.8
+      - libpcl-filters1.8
+      - libpcl-io1.8
+      - libpcl-kdtree1.8
+      - libpcl-keypoints1.8
+      - libpcl-ml1.8
+      - libpcl-octree1.8
+      - libpcl-outofcore1.8
+      - libpcl-people1.8
+      - libpcl-recognition1.8
+      - libpcl-registration1.8
+      - libpcl-sample-consensus1.8
+      - libpcl-search1.8
+      - libpcl-segmentation1.8
+      - libpcl-stereo1.8
+      - libpcl-surface1.8
+      - libpcl-tracking1.8
+      - libpcl-visualization1.8
+    zesty:
+      - libpcl-apps1.8
+      - libpcl-common1.8
+      - libpcl-features1.8
+      - libpcl-filters1.8
+      - libpcl-io1.8
+      - libpcl-kdtree1.8
+      - libpcl-keypoints1.8
+      - libpcl-ml1.8
+      - libpcl-octree1.8
+      - libpcl-outofcore1.8
+      - libpcl-people1.8
+      - libpcl-recognition1.8
+      - libpcl-registration1.8
+      - libpcl-sample-consensus1.8
+      - libpcl-search1.8
+      - libpcl-segmentation1.8
+      - libpcl-stereo1.8
+      - libpcl-surface1.8
+      - libpcl-tracking1.8
+      - libpcl-visualization1.8
 libpcl-all-dev:
   arch: [pcl]
   debian: [libpcl-dev]
```

**Comment by paulbovbel** [comment]
+1 if rosdistro maintainers agree. Another approach may be to make each package a separate rosdep and get rid of libpcl-all in lunar, but whatever works.

**Comment by mikaelarguedas** [comment]
@wkentaro FYI: the change can get in rosdistro as is without the need of creating individual keys for each package. This can be merged as soon as your PR is modified to add debian rules as well.

**Comment by wkentaro** [comment]
> the change can get in rosdistro as is without the need of creating individual keys for each package. 

@mikaelarguedas What do you mean by this? I'm not sure what is "creating individual keys for each package".

**Comment by mikaelarguedas** [comment]
> @mikaelarguedas What do you mean by this? I'm not sure what is "creating individual keys for each package".

I mean https://github.com/ros/rosdistro/pull/14598 is good as it is. No need to change anything :+1:

**Comment by wkentaro** [comment]
Released https://github.com/ros/rosdistro/pull/14642

**Comment by mikaelarguedas** [comment]
thanks! all jobs turned green, closing this now
