### ISSUE TITLE
Error in catkin_make: eigen3 not found.

### ISSUE THREAD

**Issue by sunkingac** [ros-perception/pcl_conversions#29]
Hi, 
I have installed ROS-Kinetic in Ubuntu 16.04.
And i created the catkin workspace.
I am getting the below error when building catkin with catkin_make.

              `-- +++ processing catkin package: 'beginner_tutorials'
		-- ==> add_subdirectory(beginner_tutorials)
		CMake Error at /opt/ros/kinetic/share/pcl_conversions/cmake/pcl_conversionsConfig.cmake:113 (message):
		  Project 'pcl_conversions' specifies '/usr/include/eigen3' as an include
		  dir, which is not found.  It does neither exist as an absolute directory
		  nor in '${{prefix}}//usr/include/eigen3'.  Check the issue tracker
		  'https://github.com/ros-perception/pcl_conversions/issues' and consider
		  creating a ticket if the problem has not been reported yet.
		Call Stack (most recent call first):
		  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
		  beginner_tutorials/CMakeLists.txt:6 (find_package)

		-- Configuring incomplete, errors occurred!
		See also "/home/uic34798/catkin_ws/build/CMakeFiles/CMakeOutput.log".
		See also "/home/uic34798/catkin_ws/build/CMakeFiles/CMakeError.log".
		Makefile:474: recipe for target 'cmake_check_build_system' failed
		make: *** [cmake_check_build_system] Error 1
		Invoking "make cmake_check_build_system" failed`

But the eigen folder is available in "usr/local/include".
How to fix this issue.

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

When you do so please include enough information to reproduce your problem. For example what are you compiling what packages do you have installed and how you installed everything else like eigen3 in /usr/local.
