### ISSUE TITLE
Provide a Groovy implementation so clients can support both Groovy and Hydro

### ISSUE THREAD

**Issue by jack-oquin** [ros-perception/pcl_conversions#3]
Some client packages would like to support both Groovy with PCL 1.6 and Hydro with PCL 1.7 in the same source branch.

That is currently not possible because `pcl_conversions` did not exist in Groovy.

If possible, the Groovy implementation should emulate the new Hydro interface, making it clean and easy for client programs to support both.

See: ros-perception/perception_pcl#26.

**Comment by wjwwood** [comment]
@jack-oquin I have a version for groovy in the `groovy-devel` branch now. I have also started releasing it, can you give it a try with your packages in groovy?

**Comment by jack-oquin** [comment]
I have no more time this afternoon and evening, but I'll test it tomorrow, first thing in the morning.

**Comment by wjwwood** [comment]
@davetcoleman

**Comment by davetcoleman** [comment]
I've made the changes to gazebo_ros_pkgs to support the new Groovy branch. I'll merge it in once pcl_conversions is released to Groovy public repos.

**Comment by jack-oquin** [comment]
I checked out the **groovy-devel** branch along with the **master** branch of the **velodyne** repository into a Groovy workspace. 

That is the version of the Velodyne driver you modified to work with PCL 1.7. Everything built cleanly and the Velodyne unit tests run successfully.

This will be very helpful. Thanks for doing it.

**Comment by wjwwood** [comment]
No problem, let me know if you run into any other sticking points.
